using System;
using System.Collections.Generic;
using System.IO;
using AColor = Avalonia.Media.Color;
//using Microsoft.Data.Sqlite;
using SQLite;
using AAgOpenGPS.Models;

namespace AAgOpenGPS;

public static class Seed
{
    public static string ToHex(this AColor c) => $"#{c.R:X2}{c.G:X2}{c.B:X2}";

    public static void Insert()
    {
        var dbpath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "file.db");
        //var connection = new SqliteConnection($"Filename={dbpath}");
        using (var db = new SQLiteConnection(dbpath))
        {
            var settings = new Setting
            {
                // setWindow_Location = new Point(30, 30),
                // setWindow_Size = new Size(1005, 730),
                setWindow_LocationX = 30.0,
                setWindow_LocationY = 30.0,
                setWindow_Height = 1005,
                setWindow_Width = 730,
                setWindow_Maximized = false,
                setWindow_Minimized = false,
                setMenu_isMetric = true,
                setMenu_isGridOn = true,
                setMenu_isLightbarOn = true,
                setF_CurrentDir = "",
                setF_isWorkSwitchEnabled = false,
                setIMU_rollZero = 0.0,
                setF_minHeadingStepDistance = 0.5,
                setAS_lowSteerPWM = 30,
                setAS_wasOffset = 3,
                setF_UserTotalArea = 0.0,
                setAS_minSteerPWM = 25,
                setAS_highSteerPWM = 180,
                setMenu_isSideGuideLines = false,
                setAS_countsPerDegree = 110,
                setMenu_isPureOn = true,
                setMenu_isSimulatorOn = true,
                setDisplay_lightbarCmPerPixel = 5,
                setGPS_headingFromWhichSource = "Fix",
                setGPS_SimLatitude = 53.4360564,
                setGPS_SimLongitude = -111.160047,
                setAS_snapDistance = 20.0,
                setF_isWorkSwitchManualSections = false,
                setAS_isAutoSteerAutoOn = false,
                setDisplay_lineWidth = 2,
                setTram_tramWidth = 24.0,
                setTram_passes = 1,
                setMenu_isSpeedoOn = false,
                setDisplay_colorDayFrame = "#D2D2E6",
                setDisplay_colorNightFrame = AColor.FromRgb(50, 50, 65).ToHex(),
                setDisplay_colorSectionsDay = AColor.FromRgb(27, 151, 160).ToHex(),
                setDisplay_colorFieldDay = AColor.FromRgb(100, 100, 125).ToHex(),
                setDisplay_isDayMode = true,
                setDisplay_colorFieldNight = AColor.FromRgb(60, 60, 60).ToHex(),
                setDisplay_customColors = "-62208,-12299010,-16190712,-1505559,-3621034,-16712458,-7330570,-1546731,-24406,-3289866,-2756674,-538377,-134768,-4457734,-1848839,-530985",
                setDisplay_isTermsAccepted = false,
                setGPS_isRTK = false,
                setDisplay_isStartFullScreen = false,
                setDisplay_isKeyboardOn = true,
                setIMU_rollFilter = 0.0,
                setAS_uTurnSmoothing = 14,
                setIMU_invertRoll = false,
                setAS_ackerman = 100,
                setF_isWorkSwitchActiveLow = true,
                setAS_Kp = 50,
                setSound_isUturnOn = true,
                setSound_isHydLiftOn = true,
                setDisplay_colorTextNight = AColor.FromRgb(230, 230, 230).ToHex(),
                setDisplay_colorTextDay = AColor.FromRgb(10, 10, 20).ToHex(),
                setDisplay_camZoom = 9.0,
                setDisplay_colorVehicle = "#FFFFFF",
                setDisplay_vehicleOpacity = 100,
                setDisplay_isVehicleImage = true,
                setDisplay_isTextureOn = true,
                SetGPS_udpWatchMsec = 50,
                setF_isSteerWorkSwitchManualSections = false,
                setAS_isConstantContourOn = false,
                setAS_guidanceLookAheadTime = 1.5,
                setIMU_isDualAsIMU = false,
                setAS_sideHillComp = 0.0,
                setIMU_isReverseOn = true,
                setGPS_forwardComp = 0.15,
                setGPS_reverseComp = 0.3,
                setGPS_ageAlarm = 20,
                setGPS_isRTK_KillAutoSteer = false,
                setColor_sec01 = "Color(249, 22, 10)",
                setColor_sec02 = "Color(68, 84, 254)",
                setColor_sec03 = "Color(8, 243, 8)",
                setColor_sec04 = "Color(233, 6, 233)",
                setColor_sec05 = "Color(200, 191, 86)",
                setColor_sec06 = "Color(0, 252, 246)",
                setColor_sec07 = "Color(144, 36, 246)",
                setColor_sec08 = "Color(232, 102, 21)",
                setColor_sec09 = "Color(255, 160, 170)",
                setColor_sec10 = "Color(205, 204, 246)",
                setColor_sec11 = "Color(213, 239, 190)",
                setColor_sec12 = "Color(247, 200, 247)",
                setColor_sec13 = "Color(253, 241, 144)",
                setColor_sec14 = "Color(187, 250, 250)",
                setColor_sec15 = "Color(227, 201, 249)",
                setColor_sec16 = "Color(247, 229, 215)",
                setColor_isMultiColorSections = false,
                setDisplay_customSectionColors = "-62208,-12299010,-16190712,-1505559,-3621034,-16712458,-7330570,-1546731,-24406,-3289866,-2756674,-538377,-134768,-4457734,-1848839,-530985",
                setBrand_TBrand = "AGOpenGPS",
                setHeadland_isSectionControlled = true,
                setSound_isAutoSteerOn = true,
                setRelay_pinConfig = "1,2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
                setDisplay_camSmooth = 50,
                setGPS_dualHeadingOffset = 0.0,
                setF_isSteerWorkSwitchEnabled = false,
                setF_isRemoteWorkSystemOn = false,
                setDisplay_isAutoStartAgIO = true,
                setAS_ModeXTE = 0.1,
                setAS_ModeTime = 1,
                setVehicle_toolWidth = 4.0,
                setVehicle_toolOverlap = 0.0,
                setTool_toolTrailingHitchLength = -2.5,
                setVehicle_numSections = 3,
                setSection_position1 = -2,
                setSection_position2 = -1,
                setSection_position3 = 1,
                setSection_position4 = 2,
                setSection_position5 = 0,
                setSection_position6 = 0,
                setSection_position7 = 0,
                setSection_position8 = 0,
                setSection_position9 = 0,
                setSection_position10 = 0,
                setSection_position11 = 0,
                setSection_position12 = 0,
                setSection_position13 = 0,
                setSection_position14 = 0,
                setSection_position15 = 0,
                setSection_position16 = 0,
                setSection_position17 = 0,
                purePursuitIntegralGainAB = 0,
                setVehicle_antennaHeight = 3,
                setVehicle_toolLookAheadOn = 1,
                setTool_isToolTrailing = true,
                setVehicle_toolOffset = 0,
                setTool_isToolRearFixed = false,
                setVehicle_antennaPivot = 0.1,
                setVehicle_wheelbase = 3.3,
                setVehicle_hitchLength = -1,
                setVehicle_toolLookAheadOff = 0.5,
                setVehicle_slowSpeedCutoff = 0.5,
                setVehicle_tankTrailingHitchLength = 3,
                setVehicle_minCoverage = 100,
                setVehicle_maxAngularVelocity = 0.64,
                setVehicle_maxSteerAngle = 30,
                set_youTurnExtensionLength = 20,
                setVehicle_antennaOffset = 0,
                set_youTurnDistanceFromBoundary = 2,
                setVehicle_goalPointLookAheadMult = 1.5,
                stanleyDistanceErrorGain = 1,
                stanleyHeadingErrorGain = 1,
                setVehicle_isStanleyUsed = false,
                setTool_isToolTBT = false,
                setVehicle_vehicleType = 0,
                set_youSkipWidth = 1,
                setArdSteer_setting1 = 0,
                setArdSteer_setting0 = 56,
                setVehicle_hydraulicLiftLookAhead = 2,
                setArdSteer_maxPulseCounts = 3,
                setArdMac_hydRaiseTime = 3,
                setArdMac_hydLowerTime = 4,
                setArdMac_isHydEnabled = 0,
                setTool_defaultSectionWidth = 2,
                setVehicle_toolOffDelay = 0,
                setArdMac_setting0 = 0,
                setTool_isToolFront = false,
                setVehicle_trackWidth = 1.9,
                setArdMac_isDanfoss = false,
                stanleyIntegralGainAB = 0,
                setSection_isFast = true,
                setArdMac_user1 = 1,
                setArdMac_user2 = 2,
                setArdMac_user3 = 3,
                setArdMac_user4 = 4,
                setVehicle_panicStopSpeed = 0,
                setDisplay_brightness = 40,
                set_youTurnRadius = 8.1,
                setDisplay_brightnessSystem = 40,
                setTool_isSectionsNotZones = true,
                setTool_numSectionsMulti = 20,
                setTool_zones = "2,10,20,0,0,0,0,0,0",
                setTool_sectionWidthMulti = 0.5,
                setDisplay_isBrightnessOn = false,
                setKey_hotkeys = "ACFGMNPTYVW12345678",
                setVehicle_goalPointLookAheadHold = 3,
                setTool_isSectionOffWhenOut = true,
                set_uTurnStyle = 0,
                setGPS_minimumStepLimit = 0.05,
                setAS_isSteerInReverse = false,
                setAS_functionSpeedLimit = 12,
                setAS_maxSteerSpeed = 15,
                setAS_minSteerSpeed = 0,
                setBrand_HBrand = 0, // Assuming enum value
                setBrand_WDBrand = 0, // Assuming enum value
                setIMU_fusionWeight2 = 0.06,
                setDisplay_isSvennArrowOn = false,
                setTool_isTramOuterInverted = false,
                setJobMenu_location = "200,200",
                setJobMenu_size = "640,530",
                setWindow_steerSettingsLocation = "40,40",
                setWindow_buildTracksLocation = "40,40",
                setTool_trailingToolToPivotLength = 0,
                setWindow_formNudgeLocation = "200,200",
                setWindow_formNudgeSize = "200,400",
                setAS_snapDistanceRef = 5,
                setDisplay_buttonOrder = "0,1,2,3,4,5,6,7",
                setDisplay_camPitch = -62,
                setWindow_abDrawSize = "1022,742",
                setWindow_HeadlineSize = "1022,742",
                setWindow_HeadAcheSize = "1022,742",
                setWindow_MapBndSize = "1022,742",
                setWindow_BingMapSize = "965,700",
                setWindow_BingZoom = 15,
                setWindow_QuickABLocation = "100,100",
                setDisplay_isLogElevation = false,
                setSound_isSectionsOn = true,
                setGPS_dualReverseDetectionDistance = 0.25,
                setTool_isDisplayTramControl = true,
                setAS_uTurnCompensation = 1,
                setWindow_gridSize = "400,400",
                setWindow_gridLocation = "20,20",
                setWindow_isKioskMode = false,
                setDisplay_isAutoOffAgIO = true,
                setWindow_isShutdownComputer = false,
                setDisplay_isShutdownWhenNoPower = false,
                setDisplay_isHardwareMessages = false,
                setGPS_jumpFixAlarmDistance = 0,
                setAS_deadZoneDistance = 1,
                setAS_deadZoneHeading = 10,
                setMenu_isLightbarNotSteerBar = false,
                setTool_isDirectionMarkers = true,
                setAS_numGuideLines = 10,
                setAS_deadZoneDelay = 5,
                setTram_alpha = 0.8,
                setVehicle_goalPointAcquireFactor = 0.9,
                setBnd_isDrawPivot = true,
                setDisplay_isSectionLinesOn = true,
                setDisplay_isLineSmooth = false,
                setWindow_tramLineSize = "921,676",
                setAutoSwitchDualFixOn = false,
                setAutoSwitchDualFixSpeed = 2.0
            };
            db.Insert(settings);
            //INSERT INTO Vehicle VALUES (1, 0, 'Default Vehicle', 3, 0.1, 0, 2.8, 1.9);
            //INSERT INTO Vehicle VALUES (2, 0, 'John Deere 5M', 3, 0.1, 0, 2.8, 1.9);
            var vehicle1 = new Vehicle
            {
                Type = 0,
                Name = "Default Vehicle",
                AntennaHeight = 3,
                AntennaPivot = 0.1,
                AntennaOffset = 0,
                Wheelbase = 2.8,
                TrackWidth = 1.9
            };
            db.Insert(vehicle1);
            var vehicle2 = new Vehicle
            {
                Type = 0,
                Name = "John Deere 5M",
                AntennaHeight = 3,
                AntennaPivot = 0.1,
                AntennaOffset = 0,
                Wheelbase = 2.8,
                TrackWidth = 1.9
            };
            db.Insert(vehicle2);
        }
    }
}




