using SQLite;

namespace AAgOpenGPS.Models;

public class Setting
{
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }
        public double setWindow_LocationX { get; set; }
        public double setWindow_LocationY { get; set; }
		public double setWindow_Height { get; set; }
		public double setWindow_Width { get; set; }
		public bool setWindow_Maximized { get; set; }
		public bool setWindow_Minimized { get; set; }
		public bool setMenu_isMetric { get; set; }
		public bool setMenu_isGridOn { get; set; }
		public bool setMenu_isLightbarOn { get; set; }
		public string setF_CurrentDir { get; set; }
		public bool setF_isWorkSwitchEnabled { get; set; }
		public double setIMU_rollZero { get; set; }
		public double setF_minHeadingStepDistance { get; set; }
		public byte setAS_lowSteerPWM { get; set; }
		public int setAS_wasOffset { get; set; }
		public double setF_UserTotalArea { get; set; }
		public byte setAS_minSteerPWM { get; set; }
		public byte setAS_highSteerPWM { get; set; }
		public bool setMenu_isSideGuideLines { get; set; }
		public byte setAS_countsPerDegree { get; set; }
		public bool setMenu_isPureOn { get; set; }
		public bool setMenu_isSimulatorOn { get; set; }
		public int setDisplay_lightbarCmPerPixel { get; set; }
		public string setGPS_headingFromWhichSource { get; set; }
		public double setGPS_SimLatitude { get; set; }
		public double setGPS_SimLongitude { get; set; }
		public double setAS_snapDistance { get; set; }
		public bool setF_isWorkSwitchManualSections { get; set; }
		public bool setAS_isAutoSteerAutoOn { get; set; }
		public int setDisplay_lineWidth { get; set; }
		public double setTram_tramWidth { get; set; }
		public int setTram_passes { get; set; }
		public bool setMenu_isSpeedoOn { get; set; }
		public string setDisplay_colorDayFrame { get; set; }
		public string setDisplay_colorNightFrame { get; set; }
		public string setDisplay_colorSectionsDay { get; set; }
		public string setDisplay_colorFieldDay { get; set; }
		public bool setDisplay_isDayMode { get; set; }
		public string setDisplay_colorFieldNight { get; set; }
		public string setDisplay_customColors { get; set; }
		public bool setDisplay_isTermsAccepted { get; set; }
		public bool setGPS_isRTK { get; set; }
		public bool setDisplay_isStartFullScreen { get; set; }
		public bool setDisplay_isKeyboardOn { get; set; }
		public double setIMU_rollFilter { get; set; }
		public int setAS_uTurnSmoothing { get; set; }
		public bool setIMU_invertRoll { get; set; }
		public byte setAS_ackerman { get; set; }
		public bool setF_isWorkSwitchActiveLow { get; set; }
		public byte setAS_Kp { get; set; }
		public bool setSound_isUturnOn { get; set; }
		public bool setSound_isHydLiftOn { get; set; }
		public string setDisplay_colorTextNight { get; set; }
		public string setDisplay_colorTextDay { get; set; }
		public double setDisplay_camZoom { get; set; }
		public string setDisplay_colorVehicle { get; set; }
		public int setDisplay_vehicleOpacity { get; set; }
		public bool setDisplay_isVehicleImage { get; set; }
		public bool setDisplay_isTextureOn { get; set; }
		public int SetGPS_udpWatchMsec { get; set; }
		public bool setF_isSteerWorkSwitchManualSections { get; set; }
		public bool setAS_isConstantContourOn { get; set; }
		public double setAS_guidanceLookAheadTime { get; set; }
		public bool setIMU_isDualAsIMU { get; set; }
		public double setAS_sideHillComp { get; set; }
		public bool setIMU_isReverseOn { get; set; }
		public double setGPS_forwardComp { get; set; }
		public double setGPS_reverseComp { get; set; }
		public int setGPS_ageAlarm { get; set; }
		public bool setGPS_isRTK_KillAutoSteer { get; set; }
		public string setColor_sec01 { get; set; }
		public string setColor_sec02 { get; set; }
		public string setColor_sec03 { get; set; }
		public string setColor_sec04 { get; set; }
		public string setColor_sec05 { get; set; }
		public string setColor_sec06 { get; set; }
		public string setColor_sec07 { get; set; }
		public string setColor_sec08 { get; set; }
		public string setColor_sec09 { get; set; }
		public string setColor_sec10 { get; set; }
		public string setColor_sec11 { get; set; }
		public string setColor_sec12 { get; set; }
		public string setColor_sec13 { get; set; }
		public string setColor_sec14 { get; set; }
		public string setColor_sec15 { get; set; }
		public string setColor_sec16 { get; set; }
		public bool setColor_isMultiColorSections { get; set; }
		public string setDisplay_customSectionColors { get; set; }
		public string setBrand_TBrand { get; set; }
		public bool setHeadland_isSectionControlled { get; set; }
		public bool setSound_isAutoSteerOn { get; set; }
		public string setRelay_pinConfig { get; set; }
		public int setDisplay_camSmooth { get; set; }
		public double setGPS_dualHeadingOffset { get; set; }
		public bool setF_isSteerWorkSwitchEnabled { get; set; }
		public bool setF_isRemoteWorkSystemOn { get; set; }
		public bool setDisplay_isAutoStartAgIO { get; set; }
		public double setAS_ModeXTE { get; set; }
		public int setAS_ModeTime { get; set; }
		public double setVehicle_toolWidth { get; set; }
		public double setVehicle_toolOverlap { get; set; }
		public double setTool_toolTrailingHitchLength { get; set; }
		public int setVehicle_numSections { get; set; }
		public decimal setSection_position1 { get; set; }
		public decimal setSection_position2 { get; set; }
		public decimal setSection_position3 { get; set; }
		public decimal setSection_position4 { get; set; }
		public decimal setSection_position5 { get; set; }
		public decimal setSection_position6 { get; set; }
		public decimal setSection_position7 { get; set; }
		public decimal setSection_position8 { get; set; }
		public decimal setSection_position9 { get; set; }
		public decimal setSection_position10 { get; set; }
		public decimal setSection_position11 { get; set; }
		public decimal setSection_position12 { get; set; }
		public decimal setSection_position13 { get; set; }
		public decimal setSection_position14 { get; set; }
		public decimal setSection_position15 { get; set; }
		public decimal setSection_position16 { get; set; }
		public decimal setSection_position17 { get; set; }
		public double purePursuitIntegralGainAB { get; set; }
		public double setVehicle_antennaHeight { get; set; }
		public double setVehicle_toolLookAheadOn { get; set; }
		public bool setTool_isToolTrailing { get; set; }
		public double setVehicle_toolOffset { get; set; }
		public bool setTool_isToolRearFixed { get; set; }
		public double setVehicle_antennaPivot { get; set; }
		public double setVehicle_wheelbase { get; set; }
		public double setVehicle_hitchLength { get; set; }
		public double setVehicle_toolLookAheadOff { get; set; }
		public double setVehicle_slowSpeedCutoff { get; set; }
		public double setVehicle_tankTrailingHitchLength { get; set; }
		public int setVehicle_minCoverage { get; set; }
		public double setVehicle_maxAngularVelocity { get; set; }
		public double setVehicle_maxSteerAngle { get; set; }
		public int set_youTurnExtensionLength { get; set; }
		public double setVehicle_antennaOffset { get; set; }
		public double set_youTurnDistanceFromBoundary { get; set; }
		public double setVehicle_goalPointLookAheadMult { get; set; }
		public double stanleyDistanceErrorGain { get; set; }
		public double stanleyHeadingErrorGain { get; set; }
		public bool setVehicle_isStanleyUsed { get; set; }
		public bool setTool_isToolTBT { get; set; }
		public int setVehicle_vehicleType { get; set; }
		public int set_youSkipWidth { get; set; }
		public byte setArdSteer_setting1 { get; set; }
		public byte setArdSteer_setting0 { get; set; }
		public double setVehicle_hydraulicLiftLookAhead { get; set; }
		public byte setArdSteer_maxPulseCounts { get; set; }
		public byte setArdMac_hydRaiseTime { get; set; }
		public byte setArdMac_hydLowerTime { get; set; }
		public byte setArdMac_isHydEnabled { get; set; }
		public double setTool_defaultSectionWidth { get; set; }
		public double setVehicle_toolOffDelay { get; set; }
		public byte setArdMac_setting0 { get; set; }
		public bool setTool_isToolFront { get; set; }
		public double setVehicle_trackWidth { get; set; }
		public bool setArdMac_isDanfoss { get; set; }
		public double stanleyIntegralGainAB { get; set; }
		public bool setSection_isFast { get; set; }
		public byte setArdMac_user1 { get; set; }
		public byte setArdMac_user2 { get; set; }
		public byte setArdMac_user3 { get; set; }
		public byte setArdMac_user4 { get; set; }
		public double setVehicle_panicStopSpeed { get; set; }
		public int setDisplay_brightness { get; set; }
		public double set_youTurnRadius { get; set; }
		public int setDisplay_brightnessSystem { get; set; }
		public bool setTool_isSectionsNotZones { get; set; }
		public int setTool_numSectionsMulti { get; set; }
		public string setTool_zones { get; set; }
		public double setTool_sectionWidthMulti { get; set; }
		public bool setDisplay_isBrightnessOn { get; set; }
		public string setKey_hotkeys { get; set; }
		public double setVehicle_goalPointLookAheadHold { get; set; }
		public bool setTool_isSectionOffWhenOut { get; set; }
		public int set_uTurnStyle { get; set; }
		public double setGPS_minimumStepLimit { get; set; }
		public bool setAS_isSteerInReverse { get; set; }
		public double setAS_functionSpeedLimit { get; set; }
		public double setAS_maxSteerSpeed { get; set; }
		public double setAS_minSteerSpeed { get; set; }
		public int setBrand_HBrand { get; set; } // Assuming enum value
		public int setBrand_WDBrand { get; set; } // Assuming enum value
		public double setIMU_fusionWeight2 { get; set; }
		public bool setDisplay_isSvennArrowOn { get; set; }
		public bool setTool_isTramOuterInverted { get; set; }
		public string setJobMenu_location { get; set; }
		public string setJobMenu_size { get; set; }
		public string setWindow_steerSettingsLocation { get; set; }
		public string setWindow_buildTracksLocation { get; set; }
		public double setTool_trailingToolToPivotLength { get; set; }
		public string setWindow_formNudgeLocation { get; set; }
		public string setWindow_formNudgeSize { get; set; }
		public double setAS_snapDistanceRef { get; set; }
		public string setDisplay_buttonOrder { get; set; }
		public double setDisplay_camPitch { get; set; }
		public string setWindow_abDrawSize { get; set; }
		public string setWindow_HeadlineSize { get; set; }
		public string setWindow_HeadAcheSize { get; set; }
		public string setWindow_MapBndSize { get; set; }
		public string setWindow_BingMapSize { get; set; }
		public int setWindow_BingZoom { get; set; }
		public string setWindow_QuickABLocation { get; set; }
		public bool setDisplay_isLogElevation { get; set; }
		public bool setSound_isSectionsOn { get; set; }
		public double setGPS_dualReverseDetectionDistance { get; set; }
		public bool setTool_isDisplayTramControl { get; set; }
		public double setAS_uTurnCompensation { get; set; }
		public string setWindow_gridSize { get; set; }
		public string setWindow_gridLocation { get; set; }
		public bool setWindow_isKioskMode { get; set; }
		public bool setDisplay_isAutoOffAgIO { get; set; }
		public bool setWindow_isShutdownComputer { get; set; }
		public bool setDisplay_isShutdownWhenNoPower { get; set; }
		public bool setDisplay_isHardwareMessages { get; set; }
		public int setGPS_jumpFixAlarmDistance { get; set; }
		public int setAS_deadZoneDistance { get; set; }
		public int setAS_deadZoneHeading { get; set; }
		public bool setMenu_isLightbarNotSteerBar { get; set; }
		public bool setTool_isDirectionMarkers { get; set; }
		public int setAS_numGuideLines { get; set; }
		public int setAS_deadZoneDelay { get; set; }
		public double setTram_alpha { get; set; }
		public double setVehicle_goalPointAcquireFactor { get; set; }
		public bool setBnd_isDrawPivot { get; set; }
		public bool setDisplay_isSectionLinesOn { get; set; }
		public bool setDisplay_isLineSmooth { get; set; }
		public string setWindow_tramLineSize { get; set; }
		public bool setAutoSwitchDualFixOn { get; set; }
		public double setAutoSwitchDualFixSpeed { get; set; }
}
